import chess

board = chess.Board()
print(board)
print(board.legal_moves)
print(chess.Move.from_uci('a2a5') in board.legal_moves)
board.push_san("e4")
board.push_san("e5")
board.push_san("Qh5")
board.push_san("Nc6")
board.push_san("Bc4")
board.push_san("Nf6")
board.push_san("Qxf7")
print("wtf")
print(board.is_checkmate())
print(board)
print(chess.BLACK)
print(chess.WHITE)
print(chess.BISHOP)
print(chess.piece_name(1))
print(chess.piece_symbol(3))
print(chess.C1)
print(chess.SQUARES)
print(chess.FILE_NAMES)
print(chess.RANK_NAMES)
print(chess.square(3,4))
print(chess.square_file(0))
print(chess.square_rank(0))
print(chess.square_name(5))
print(chess.square_distance(13,5))
print(chess.square_mirror(0))
print(board)
print(board.move_stack)
print(board.pieces(1,1).tolist())


